### PR TITLE
first try at diff eq conversion

### PR DESCRIPTION
**Pull request by davidfarmer**
Files in the ptxDE direcrtory

Top level file is index.ptx .  Probably it needs hand editing because the
conversion thought it was doing an entire book.

I can update the script and re-run if you notice any issues.

I glanced through the files but did not try compiling.

### CODE REVIEW

**Comment by sean-fitzpatrick** [comment]
Thanks. These used the same preamble as the rest of the APEX book.
Some hand editing will be needed. But the plan is that these should eventually drop in with the rest of the book, using the index.ptx file there.

**Comment by sean-fitzpatrick** [comment]
It looks good. The only thing that didn't go through cleanly: evidently Greg's LaTeX code for examples and figures doesn't work in the appendix. (Maybe a numbering thing?)
So instead of \example and \mfigure, there's \appendixexample and \appendixmfigure.

But it's not that much content, so I don't think it'll be much work to take the text from each example and wrap it in the correct markup. And figures have to be redone anyway to pull in the TikZ code.

**Comment by davidfarmer** [comment]
I'll make that change and send another pull request.

**Comment by sean-fitzpatrick** [comment]
Thanks. I've asked Lyle if he can look it over. I can pay him a few more hours before we run out of money, and there are no classes next week, so he might have time.

**Pull request merged**
